- .gitignore
- poetry.lock
- pyproject.toml
- src/cli.py
- src/commands/install/install.py
- src/utils/__init__.py
- src/utils/standard_log_formatter.py
- added basic logging configuration
NOTE:
Test may require adding a custom Formatter.
> Setup logging

- poetry.lock
- pyproject.toml
- src/commands/test/cheatcodes/cheat_sources/cheats.cairo
- src/commands/test/cheatcodes/cheats_test.py
- src/commands/test/cheatcodes/syscall_handler.py
- src/commands/test/cheatcodes/test_cheats.cairo
- src/commands/test/collector.py
- src/commands/test/runner.py
- src/utils/modules.py
- src/utils/starknet_compilation.py
Implemented `warp`, `roll` and `start_prank` + `stop_prank`
> Simple cheatcodes implementation

- src/commands/test/cheatcodes/cheat_sources/cheats.cairo
- src/commands/test/cheatcodes/syscall_handler.py
- src/commands/test/cheatcodes/test_cheats.cairo
- added `mockCall` cheatcode
- added `clearMockCall` cheatcode
> Add "mockCall" cheat code

- src/commands/build/build_project_test.py
- src/utils/starknet_compilation.py
- website/docs/tutorials/guides/compiling.md
- website/docusaurus.config.js
- added missing main file exception
- added "Project compilation" docs
> Add compilation docs

- src/commands/test/runner.py
Tested manually.
Merge it after approving.
> Hotfix `except_revert`

- website/docs/tutorials/01-introduction.md
Been looking forward to this project going live. Great work! Can't wait to give it a shot
> Fix typo in docs/tutorials/01-introduction.md

- protostar.py
> Check for being the entry point when executing the CLI

- templates/default/src/main.cairo
- templates/default/tests/test_main.cairo
- tests/e2e/test_testing.py
- used unit test workflow in the generated test file
> Simplify test file generated by `protostar init`

- poetry.lock
- pyproject.toml
> Update `cairo-lang` to version 0.8.2.1

- poetry.lock
- pyproject.toml
- src/commands/__init__.py
- src/commands/deploy/__init__.py
- src/commands/deploy/deploy_command.py
- src/protostar_cli.py
Deployment flow:
1. A user defines networks (or Protostar provides default configuration as a result of running `protostar init`).
2. A user chooses a defined network during deployment. 
`protostar.toml`
```toml
[protostar.network.devnet]
feeder_gateway_url = "http://127.0.0.1:5050/"
gateway_url = "http://127.0.0.1:5050/"
[protostar.network.testnet]
network = "alpha-goerli"
[protostar.network.mainnet]
network = "alpha-mainnet"
[protostar.deploy]
contract = "main"
inputs = ""
network = "devnet"
token = ""
```
> Deploy command interface

- protostar/commands/test/starkware/__init__.py
- protostar/commands/test/starkware/cheatable_syscall_handler.py
- protostar/commands/test/test_cases.py
- protostar/commands/test/test_environment_exceptions.py
- protostar/commands/test/test_execution_environment.py
- protostar/commands/test/test_runner.py
- protostar/protostar_exception.py
- protostar/start.py
- tests/integration/cheatcodes/other/test_other_cheatcodes.cairo
- tests/integration/cheatcodes/other/test_other_cheatcodes.py
- fixed freezing
- made cheatcode errors to be pretty printed
> Fix Protostar freezing

- website/docs/tutorials/guides/testing.md
Finally getting around to giving this a shot :) noticed this while starting out
Overall super sleek! Especially for Mac M1 setup, compared to manually wrangling the environment issues there
> Minor fix for example in testing tutorial

- protostar/commands/test/examples/basic.cairo
- protostar/commands/test/examples/basic_with_constructor.cairo
- protostar/commands/test/examples/broken/basic_broken.cairo
- protostar/commands/test/examples/failure/test_basic_failure.cairo
- templates/default/src/main.cairo
- tests/e2e/fixtures/basic.cairo
- tests/e2e/fixtures/proxy_contract.cairo
- tests/e2e/fixtures/test_failed.cairo
- tests/e2e/performance/test_performance_testing.py
- tests/e2e/test_deploying/contract_with_constructor.cairo
- tests/integration/cheatcodes/deploy_contract/basic_contract.cairo
- tests/integration/cheatcodes/deploy_contract/proxy_contract.cairo
- tests/integration/cheatcodes/expect_events/basic_contract.cairo
- tests/integration/cheatcodes/expect_revert/expect_revert_test.cairo
- tests/integration/testing_hooks/basic_contract.cairo
> Remove `%builtins` directive from codebase

- website/docs/tutorials/guides/testing.md
> [setup_state::03] Docs

- poetry.lock
- protostar/commands/deploy/starkware/starknet_cli.py
- protostar/commands/test/starkware/cheatable_syscall_handler.py
- protostar/commands/test/test_execution_environment.py
- protostar/commands/test/test_runner.py
- protostar/utils/starknet_compilation.py
- pyproject.toml
- scripts/deploy_prerelease.py
- tests/e2e/test_deploying.py
- tests/integration/deploying/deploy_command_test.py
- tests/integration/deploying/deploy_test.py
This PR makes an initial effort to support cairo 0.9
> [0.9.0::01] Make tests pass, fix imports and interfaces changes

- protostar/utils/config/examples/kebab_case/protostar.toml
- protostar/utils/config/project.py
- protostar/utils/config/project_test.py
- website/docs/tutorials/01-introduction.md
- website/docs/tutorials/03-project-initialization.md
- website/docs/tutorials/guides/deploying.md
I didn't deprecate using underscores.
> Support kebab case in `protostar.toml`

- README.md
> Updates mypy link

- protostar/commands/init/init_command.py
- protostar/commands/init/project_creator/__init__.py
- protostar/commands/init/project_creator/adapted_project_creator.py
- protostar/commands/init/project_creator/new_project_creator.py
- protostar/protostar_cli.py
- protostar/utils/__init__.py
- protostar/utils/input_requester.py
I forgot to push the change before merging previous PR.
> Rename Requester to `InputRequster` + hot fix

- website/docs/tutorials/guides/testing.md
> Hotfix docs

- protostar/commands/build/build_command.py
- protostar/commands/build/project_compiler.py
- protostar/commands/test/test_command.py
- protostar/commands/test/test_runner.py
- protostar/commands/test/test_scheduler.py
- protostar/utils/starknet_compilation.py
- tests/e2e/test_building.py
- tests/e2e/test_testing.py
- website/docs/cli-reference.md
- website/docs/tutorials/guides/compiling.md
Protostar will try to again compiling the contract if the account contract error is detected.
> Detect account-contracts

- protostar/protostar_cli.py
- protostar/start.py
- tests/e2e/test_building.py
Added command timing, because command classes are abstracted I added logging to the ProtostarCLI object destructor.
> Added command timing

- protostar/commands/test/test_command.py
- website/docs/cli-reference.md
> Updated description

- protostar/commands/test/cheatcodes/declare_cheatcode.py
- protostar/starknet/cheatcode.py
> Add event ABI in default cheatcode implementation

- protostar/commands/test/test_collector.py
- protostar/commands/test/test_command.py
- protostar/utils/compiler/pass_managers.py
- protostar/utils/starknet_compilation.py
- scripts/custom_checks.sh
- tests/e2e/test_testing.py
- tests/integration/compilation/collector_contract.cairo
- tests/integration/compilation/starknet_compilation_test.py
- tests/integration/compilation/test_collector_compilation_test.py
- website/docs/cli-reference.md
Performance boost compared to `--fast-collection` around 30%
Performance boost compared to default strategy ~10fold
It deprecates fast-collecting, I will remove it in a separate PR, currently only added an assert
> Improved default collection strategy

- protostar/cli/argument_parser_facade.py
- protostar/cli/argument_parser_facade_test.py
- protostar/cli/command.py
- protostar/commands/test/test_command.py
- protostar/commands/test/testing_seed.py
- protostar/commands/test/testing_seed_test.py
- protostar/commands/test/testing_summary.py
- tests/e2e/test_fuzzing.py
- tests/e2e/test_testing.py
- tests/integration/fuzzing/fuzzing_test.py
- website/docs/cli-reference.md
> Show & set testing seed

- protostar/commands/test/cheatcodes/__init__.py
- protostar/commands/test/cheatcodes/given_cheatcode.py
- protostar/commands/test/environments/fuzz_test_execution_environment.py
- protostar/commands/test/fuzzing/exceptions.py
- protostar/commands/test/fuzzing/hypothesis/aio.py
- protostar/commands/test/fuzzing/hypothesis/reporter.py
- protostar/commands/test/fuzzing/hypothesis/runs_counter.py
- protostar/commands/test/fuzzing/hypothesis/runs_counter_test.py
- protostar/commands/test/fuzzing/strategies/__init__.py
- protostar/commands/test/fuzzing/strategies/felt.py
- protostar/commands/test/fuzzing/strategy_descriptor.py
- protostar/commands/test/fuzzing/strategy_selector.py
- protostar/commands/test/fuzzing/strategy_selector_test.py
- tests/integration/fuzzing/fuzzing_test.py
- tests/integration/fuzzing/strategies_test.cairo
Review commit by commit.
fix #421
> Fuzz testing strategies

- protostar/commands/__init__.py
- protostar/composition_root.py
- protostar/configuration_profile_cli.py
- protostar/migrator/__init__.py
- protostar/protostar_cli.py
- protostar/protostar_cli_test.py
- protostar/protostar_toml/__init__.py
- protostar/start.py
- protostar/start_test.py
- pyproject.toml
- scripts/generate_reference_docs.py
- scripts/generate_reference_docs_test.py
- moved instantiation from `protostar_cli.py` to `composition_root.py`
- refactored:
- `start.py`
- `start_test.py`
- `protostar_cli.py` 
- moved cli_reference_docs snapshot test to `generate_reference_docs_test.py` and update `poe test_integration`
> Composition root

- tests/integration/fuzzing/fuzzing_test.py
- tests/integration/fuzzing/issue_590_test.cairo
> Add a test for #590 to our testing suite

- tests/e2e/conftest.py
- tests/e2e/test_misc_commands.py
- tests/e2e/test_testing.py
> Make E2E tests independent of CWD

- protostar/protostar_toml/protostar_toml_version_checker.py
- protostar/protostar_toml/protostar_toml_version_checker_test.py
- protostar/utils/protostar_directory.py
- pyproject.toml
- scripts/deploy.py
- tests/e2e/conftest.py
- tests/e2e/test_misc_commands.py
- changed latest supported version from 0.3.0 to 0.1.0
- renamed config name from `last...` to `latest...`
> Fix latest supported version

- website/docs/tutorials/06-deploying/02-migrations/call.md
Merge after https://github.com/software-mansion/protostar/pull/618
> Add `call` migration cheatcode doc

- binary_entrypoint.py
- protostar/composition_root.py
- protostar/protostar_cli.py
- protostar/start.py
- improved initial responsiveness (the initialization time is the same though)
- fixed execution time
https://user-images.githubusercontent.com/9629577/184952214-0358b953-0dd4-49a9-9b32-6dc00de46136.mov
> Add initial activity indicator and fix execution time

- protostar/commands/test/test_collector.py
- protostar/commands/test/test_collector_test.py
- protostar/commands/test/test_runner.py
- protostar/commands/test/test_suite.py
- protostar/utils/starknet_compilation.py
- tests/benchmarks/test_benchmark.py
- tests/integration/fuzzing/fuzzing_test.py
> Extract TestCase class

- protostar/commands/test/test_case_runners/test_case_runner.py
Little change which may slightly increases readability of TestCaseRunner code by abstracting the logic of measuring test time. Not necessary to be merged, maybe I'm overcomplicating things...
> Abstract away test execution time measurement

- pytest.ini
This PR removes pytest pop-up:
> Disable deprecation warnings

- website/docs/tutorials/04-compiling.md
- website/docs/tutorials/08-formatting.md
> `protostar format` in docs

- protostar/commands/declare/declare_command.py
- protostar/commands/deploy/deploy_command.py
- protostar/starknet_gateway/__init__.py
- protostar/starknet_gateway/gateway_response.py
- protostar/starknet_gateway/gateway_response_test.py
- protostar/starknet_gateway/starknet_request.py
- protostar/starknet_gateway/starknet_request_test.py
- tests/e2e/test_deploying.py
- tests/e2e/test_migrating.py
> Displaying adequate fields in hex

- README.md
- install_testing_harness.sh
- tests/e2e/installation_script/conftest.py
- tests/e2e/installation_script/install_testing_harness.sh
- tests/e2e/installation_script/test_install_sh.py
- tests/e2e/test_install_sh.py
- added info how to install a specific version to the README because we can't deploy docs until the next release
- added test cases checking installing specific version
- refactored `install.sh` test suite
- moved testing harness to the test directory
> Improved `install.sh` test suite. Updated README.md

- protostar/commands/migrate/migrate_command_test.py
- protostar/commands/test/cheatcodes/given_cheatcode.py
- protostar/commands/test/cheatcodes/load_cheatcode.py
- protostar/commands/test/cheatcodes/mock_call_cheatcode.py
- protostar/commands/test/cheatcodes/prepare_cheatcode.py
- protostar/commands/test/cheatcodes/start_prank_cheatcode.py
- protostar/commands/test/test_environment_exceptions.py
- protostar/migrator/cheatcodes/migrator_call_cheatcode.py
- protostar/migrator/cheatcodes/migrator_declare_cheatcode.py
- protostar/migrator/cheatcodes/migrator_invoke_cheatcode.py
This small change I came up with recently. It's a little QoL improvement as it removes a need for 2-5 keystrokes when coding.
> Allow passing `self` as first argument of `CheatcodeException`

- poetry.lock
- pyproject.toml
> Bump cairo-lang and starknet.py deps, temporarily disable starknet-devnet dep

- protostar/commands/test/environments/test_execution_environment.py
- protostar/starknet/execution_environment.py
- protostar/starknet/forkable_starknet.py
- protostar/starknet_gateway/gateway_facade.py
- protostar/utils/compiler/pass_managers.py
> Adjust Protostar to changes in Cairo AST

- protostar/cli/signable_command_util.py
> Temporarily fix typechecks related to missing transactions v1 support

- protostar/commands/test/cheatcodes/reflect/cairo_struct.py
- protostar/commands/test/cheatcodes/reflect/cairo_struct_test.py
- protostar/commands/test/fuzzing/exceptions.py
- protostar/commands/test/test_case_runners/fuzz_test_case_runner.py
- protostar/commands/test/test_case_runners/setup_case_runner.py
- protostar/commands/test/test_case_runners/test_case_runner.py
- protostar/commands/test/test_environment_exceptions.py
- protostar/commands/test/test_result_formatter.py
- protostar/commands/test/test_results.py
- protostar/commands/test/test_runner.py
- protostar/commands/test/testing_summary.py
- tests/integration/cheatcodes/load/load_test.py
- tests/integration/cheatcodes/mock_call/mock_call_test.py
- tests/integration/cheatcodes/prank/prank_test.py
- tests/integration/cheatcodes/reflect/reflect_test.py
- tests/integration/conftest.py
- tests/integration/constructor_in_tested_file/constructor_in_tested_file_test.py
- tests/integration/fuzzing/fuzzing_test.py
- tests/integration/fuzzing_strategies/fuzzing_strategies_test.py
- tests/integration/testing_hooks/testing_hooks_test.py
- added BreakingReportedException, makes the tests finish with the BROKEN status
- renamed TestingSummary.broken -> TestingSummary.broken_suites
- added TestingSummary.broken for BrokenTestCaseResults
- fixed tests
This is a potential breaking change.
> Added BrokenTestCaseResult

- tests/data/contracts.py
- tests/integration/fuzzing_strategies/map_and_filter_test.cairo
- tests/integration/fuzzing_strategies/one_of_test.cairo
> Migrate Cairo code vol. 3

- protostar/cli/signable_command_util.py
- protostar/commands/test/cheatcodes/declare_cheatcode.py
- protostar/commands/test/cheatcodes/deploy_cheatcode.py
- protostar/commands/test/cheatcodes/expect_events_cheatcode.py
- protostar/commands/test/cheatcodes/load_cheatcode.py
- protostar/commands/test/cheatcodes/mock_call_cheatcode.py
- protostar/commands/test/cheatcodes/prepare_cheatcode.py
- protostar/commands/test/cheatcodes/roll_cheatcode.py
- protostar/commands/test/cheatcodes/start_prank_cheatcode.py
- protostar/commands/test/cheatcodes/store_cheatcode.py
- protostar/commands/test/cheatcodes/warp_cheatcode.py
- protostar/commands/test/starkware/test_execution_state.py
- protostar/starknet/cheatable_cached_state.py
- protostar/starknet/cheatable_cairo_function_runner.py
- protostar/starknet/cheatable_execute_entry_point.py
- protostar/starknet/cheatable_invoke_function.py
- protostar/starknet/cheatable_state.py
- protostar/starknet/cheatable_syscall_handler.py
- protostar/starknet/cheatcode.py
- protostar/starknet/forkable_starknet.py
> Hack: Move cheatable state to CachedState

- protostar/commands/test/cheatcodes/declare_cheatcode.py
- protostar/commands/test/cheatcodes/deploy_cheatcode.py
- protostar/commands/test/cheatcodes/prepare_cheatcode.py
> Align deploy and declare cheatcodes with new state implementation

- tests/benchmarks/test_benchmark.py
- tests/integration/protostar_fixture.py
Two of them are still failing probably due to problems with devnet, leaving them for now
> Fixed some migrator tests

- protostar/commands/test/cheatcodes/deploy_cheatcode.py
This fixes the test with pranks. Also verified #785 and it seems like they are working.
> Fix deployment issues with constructor

- protostar/commands/cairo_migrate/cairo_migrate_command.py
- website/docs/cli-reference.md
- website/docs/tutorials/04-compiling.md
- website/docs/tutorials/05-dependencies-management.md
- website/docs/tutorials/06-deploying/01-cli.md
- website/docs/tutorials/06-deploying/02-migrations/README.md
- website/docs/tutorials/06-deploying/02-migrations/call.md
- website/docs/tutorials/06-deploying/02-migrations/declare.md
- website/docs/tutorials/06-deploying/02-migrations/deploy-contract.md
- website/docs/tutorials/06-deploying/02-migrations/invoke.md
- website/docs/tutorials/07-testing/01-deploying-contracts.md
- website/docs/tutorials/07-testing/02-cheatcodes/README.md
- website/docs/tutorials/07-testing/02-cheatcodes/assume.md
- website/docs/tutorials/07-testing/02-cheatcodes/deploy.md
- website/docs/tutorials/07-testing/02-cheatcodes/expect-events.md
- website/docs/tutorials/07-testing/02-cheatcodes/expect-revert.md
- website/docs/tutorials/07-testing/02-cheatcodes/load.md
- website/docs/tutorials/07-testing/02-cheatcodes/max-examples.md
- website/docs/tutorials/07-testing/02-cheatcodes/mock-call.md
- website/docs/tutorials/07-testing/02-cheatcodes/reflect.md
- website/docs/tutorials/07-testing/02-cheatcodes/reject.md
- website/docs/tutorials/07-testing/02-cheatcodes/roll.md
- website/docs/tutorials/07-testing/02-cheatcodes/start-prank.md
- website/docs/tutorials/07-testing/02-cheatcodes/store.md
- website/docs/tutorials/07-testing/02-cheatcodes/warp.md
- website/docs/tutorials/07-testing/03-fuzzing/README.md
- website/docs/tutorials/07-testing/README.md
> Update docs to Cairo 0.10 syntax

- poetry.lock
- pyproject.toml
> Use master devnet temporarily

- protostar/commands/test/cheatcodes/declare_cheatcode.py
- protostar/commands/test/starkware/test_execution_state.py
- protostar/commands/test/test_runner.py
- protostar/starknet/cheatable_cached_state.py
- tests/benchmarks/test_benchmark.py
- tests/e2e/test_cairo_010_migrate.py
> Added `class_hash -> contract_path` 

- install.sh
I need to add more code to this file without making a mess.
Related: https://github.com/software-mansion/protostar/issues/605
> Refactor `install.sh`

- website/docs/tutorials/07-testing/02-cheatcodes/assume.md
- website/docs/tutorials/07-testing/02-cheatcodes/given.md
- website/docs/tutorials/07-testing/02-cheatcodes/reject.md
- website/docs/tutorials/07-testing/02-cheatcodes/strategy.md
- website/docs/tutorials/07-testing/03-fuzzing/strategies.md
fix #633, expands them with new features info
> Fuzzing strategies documentation

- protostar/testing/fuzzing/strategies/felts.py
- protostar/testing/fuzzing/strategies/strategies_test.py
- tests/integration/fuzzing_strategies/felts_test.cairo
- tests/integration/fuzzing_strategies/fuzzing_strategies_test.py
- website/docs/tutorials/07-testing/03-fuzzing/strategies.md
> Add rc_bound kwarg to felts strategy

- website/docs/tutorials/07-testing/02-cheatcodes/deploy-contract.md
Updated grammatical errors in the info section of the deploy_contract
> updated grammatical errors

- tests/integration/deploying/declare_command_test.py
> Use GatewayClient instead of request in one test

- website/docs/tutorials/05-dependencies-management.md
> Update OZ usage in dependency management docs

- tests/e2e/fixtures/test_fuzz_single.cairo
- tests/e2e/test_fuzzing.py
Adding a test that checks whether the seed is different every time we run the fuzzer.
#712
> Add test for checking if the seed changes every time

- protostar/testing/fuzzing/strategies/__init__.py
- protostar/testing/fuzzing/strategies/short_strings.py
- protostar/testing/fuzzing/strategies/strategies_test.py
- protostar/testing/fuzzing/strategy_collector_test.py
- tests/integration/fuzzing_strategies/fuzzing_strategies_test.py
- tests/integration/fuzzing_strategies/short_strings_test.cairo
- website/docs/tutorials/07-testing/03-fuzzing/strategies.md
Adding the short-string strategy plus tests.
#580
> Add short string strategy

- .github/workflows/assign_pr_author.yml
It's easier to distinguish authors by icon than by name.
> Add auto author assign action

- protostar/profiler/contract_profiler.py
- protostar/profiler/transaction_profiler.py
- protostar/profiler/transaction_profiler_test.py
- protostar/starknet/cheatable_execute_entry_point.py
This PR includes:
- Made Instruction ID alghoritm deterministic, removed randomness
- Added unit test for some functions
- Frozen all dataclasses for safety reasons
> Fixed InstructionID issue, partial refactor of transaction profiler

- website/docs/tutorials/02-installation.md
> Add Protostar Versioning section

- protostar/migrator/cheatcodes/migrator_invoke_cheatcode.py
- protostar/starknet_gateway/gateway_facade.py
- tests/e2e/test_migrating/migration_signed_invokes.cairo
- tests/integration/migrator/migrator_invoke_cheatcode_test.py
- website/docs/tutorials/06-deploying/02-migrations/invoke.md
> Unify max-fee interfaces across commands and cheatcodes

- website/docs/tutorials/06-deploying/01-cli.md
> Update the `PROTOSTAR_ACCOUNT_PRIVATE_KEY` variable name in the docs

- protostar/starknet_gateway/gateway_facade.py
- tests/integration/deploying/declare_command_test.py
This only surfaced in the newest devnet release, so i'm including this bugfix in the 0.10.1 milestone.
> Fix waiting for declare acceptance with fee errors

- website/docs/tutorials/07-testing/README.md
> Expand documentation on setup hooks

- protostar/scripting/__init__.py
- protostar/scripting/deployments/__init__.py
- protostar/scripting/deployments/call.py
- protostar/scripting/deployments/declare.py
- protostar/scripting/deployments/invoke.py
- protostar/scripting/typing.py
- protostar/scripting/version.py
cc #998
---
**Stack**:
- #1035
- #1034 ⬅
- #1017
- #1016
> Prototype initial deploy scripting API

- protostar/commands/install/install_command.py
- protostar/configuration_file/configuration_file.py
> Suggest adding cairo-path to the protostar.toml after adding a package

- .github/CODEOWNERS
commit-id:47bcb8a0
---
**Stack**:
- #1059
- #1017
- #1016
- #1035 ⬅
> Set CODEOWNERS for scripting modules

- protostar/composition_root.py
- protostar/protostar_cli.py
- protostar/protostar_cli_test.py
- protostar/self/__init__.py
- protostar/self/conftest.py
- protostar/self/protostar_compatibility_with_project_checker.py
- protostar/self/protostar_compatibility_with_project_checker_test.py
Display warnings if a Protostar project is not compatible with Protostar.
Related #477
> Redesigning `protostar.toml` 18 — Connect compatibility checker

- website/docs/tutorials/08-interacting-with-starknet/03-deploy-account.md
> Add `deploy-account` doc

- pyproject.toml
Closes https://github.com/software-mansion/protostar/issues/1092
> Disable alphabetical sort in the isort configuration

- protostar/starknet/cheatable_cached_state.py
- protostar/starknet/cheatable_syscall_handler.py
- protostar/testing/cheatcodes/__init__.py
- protostar/testing/cheatcodes/expect_call_cheatcode.py
- protostar/testing/environments/test_execution_environment.py
- protostar/testing/test_environment_exceptions.py
- protostar/testing/test_environment_exceptions_test.py
- tests/integration/cheatcodes/expect_call/basic_contract.cairo
- tests/integration/cheatcodes/expect_call/expect_call_test.cairo
- tests/integration/cheatcodes/expect_call/expect_call_test.py
- website/docs/tutorials/08-testing/02-cheatcodes/expect-call.md
> Add `expect_call` cheatcode

- website/docs/tutorials/08-deploying/02-migrations/README.md
- website/docs/tutorials/08-deploying/02-migrations/_category_.yaml
fix #1001
commit-id:b2116407
---
**Stack**:
- #1119
- #1117 ⬅
> Deprecate migrations in documentation

- protostar/commands/migrate_command.py
> Warn users of migrations about their future deletion

- binary_entrypoint.py
- poetry.lock
- pyproject.toml
commit-id:75c8bbdc
---
**Stack**:
- #1132
- #1137
- #1131
- #1134 ⬅
> Do not bundle GitPython with Protostar

- .github/workflows/checks.yml
- CONTRIBUTING.md
- codecov.yml
- poetry.lock
- pyproject.toml
> Remove code coverage from the project

- .github/workflows/checks.yml
- poetry.lock
- pyproject.toml
https://pytest-xdist.readthedocs.io/en/latest/distribution.html
> Use pytest-xdist to further parallelize tests

- protostar/cli/common_arguments.py
- protostar/starknet_gateway/block_explorer/block_explorer.py
- protostar/starknet_gateway/block_explorer/block_explorer_factory.py
- protostar/starknet_gateway/block_explorer/combined_block_explorer.py
- protostar/starknet_gateway/block_explorer/fake_block_explorer.py
- protostar/starknet_gateway/block_explorer/stark_scan_block_explorer.py
- protostar/starknet_gateway/block_explorer/viewblock_block_explorer.py
- protostar/starknet_gateway/block_explorer/voyager_block_explorer.py
- website/docs/cli-reference.md
Show two main competing block explorers by default.
Related #899
> Show StarkScan and Voyager links by default

- website/docs/tutorials/07-testing/02-cheatcodes/expect-events.md
> Add `data-transformer` usage example in expect-events docs

- protostar/cli/__init__.py
- protostar/cli/messenger_factory.py
- protostar/io/__init__.py
- protostar/io/output.py
commit-id:92df4f6a
---
**Stack**:
- #1146
- #1132
- #1137
- #1131 ⬅
> Set up output formatting infrastructure

- protostar/commands/call_command.py
- protostar/composition_root.py
- tests/e2e/test_gateway_commands.py
- tests/integration/commands/call_command_test.py
- tests/integration/protostar_fixture.py
- website/docs/cli-reference.md
- website/docs/tutorials/08-interacting-with-starknet/02-call.md
commit-id:62ce5726
---
**Stack**:
- #1146
- #1132
- #1137 ⬅
> Implement structured output for `call` command

- protostar/commands/format_command.py
- protostar/composition_root.py
- protostar/formatter/formatter.py
- protostar/formatter/formatting_result.py
- protostar/formatter/formatting_result_test.py
- protostar/formatter/formatting_summary.py
- protostar/formatter/formatting_summary_test.py
- tests/integration/formatter/formatter_test.py
- tests/integration/protostar_fixture.py
commit-id:1d51ef78
Signed-off-by: Marek Kaput <marek.kaput@swmansion.com>
---
**Stack**:
- #1154
- #1146
- #1132 ⬅
> Implement structured output for `format` command

- poetry.lock
- pyproject.toml
> Bump Starknet.py

- protostar/commands/invoke_command.py
- protostar/composition_root.py
- tests/e2e/test_gateway_commands.py
- tests/integration/protostar_fixture.py
- website/docs/cli-reference.md
- website/docs/tutorials/08-interacting-with-starknet/01-invoke.md
commit-id:7d51a392
Signed-off-by: Marek Kaput <marek.kaput@swmansion.com>
---
**Stack**:
- #1169
- #1160
- #1166
- #1165
- #1154 ⬅
> Implement structured output for `invoke` command

- protostar/commands/deploy_account_command.py
- protostar/composition_root.py
- protostar/starknet_gateway/gateway_facade.py
- tests/e2e/test_gateway_commands.py
- tests/integration/protostar_fixture.py
- website/docs/cli-reference.md
commit-id:64867551
Signed-off-by: Marek Kaput <marek.kaput@swmansion.com>
---
**Stack**:
- #1169
- #1160 ⬅
> Implement structured output for `deploy-account` command

- protostar/argument_parser/argument.py
- protostar/argument_parser/command.py
- protostar/cli/common_arguments.py
- protostar/cli/protostar_argument.py
- protostar/cli/protostar_command.py
- protostar/commands/build_command.py
- protostar/commands/declare_command.py
- protostar/commands/deploy_account_command.py
- protostar/commands/deploy_command.py
- protostar/commands/install/install_command.py
- protostar/commands/invoke_command.py
- protostar/commands/migrate_command.py
- protostar/commands/remove/remove_command.py
- protostar/commands/update/update_command.py
Remove duplication in argument declarations.
> Refactor: share common arguments

- protostar/testing/environments/fuzz_test_execution_environment.py
- tests/e2e/fixtures/test_fuzz.cairo
- tests/integration/cheatcodes/assume_and_reject/assume_and_reject_test.cairo
- tests/integration/cheatcodes/assume_and_reject/assume_and_reject_together_test.cairo
- tests/integration/fuzzing/basic_test.cairo
- tests/integration/fuzzing/fuzzing_test.py
- tests/integration/fuzzing/hypothesis_multiple_errors_test.cairo
- tests/integration/fuzzing/max_examples_in_setup_case_test.cairo
- tests/integration/fuzzing/max_examples_in_setup_hook_test.cairo
- tests/integration/fuzzing/max_examples_invalid_arguments_test.cairo
- tests/integration/fuzzing/parameterized_test.cairo
- tests/integration/fuzzing/shared_state_test.cairo
- tests/integration/fuzzing/state_isolation_test.cairo
> Raise error when test parameters not found

- docs_generator/reference_docs_generator.py
- docs_generator/reference_docs_generator_test.py
- protostar/argument_parser/argument.py
- protostar/argument_parser/argument_parser_facade.py
- protostar/argument_parser/argument_parser_facade_test.py
- protostar/cli/common_arguments.py
- protostar/cli/protostar_arg_type.py
- protostar/commands/build_command.py
- protostar/commands/cairo_migrate_command.py
- protostar/commands/call_command.py
- protostar/commands/deploy_command.py
- protostar/commands/format_command.py
- protostar/commands/invoke_command.py
- protostar/commands/test/test_command.py
- protostar/start.py
- tests/integration/commands/call_command_test.py
- tests/integration/commands/getter_contract.cairo
- tests/integration/commands/invoke_command_test.py
- tests/integration/deploying/deploy_command_test.py
- tests/integration/protostar_fixture.py
- website/docs/cli-reference.md
- website/docs/tutorials/08-interacting-with-starknet/01-invoke.md
- website/docs/tutorials/08-interacting-with-starknet/02-call.md
> Support different inputs format in CLI

- protostar/starknet/cheatable_cached_state.py
- protostar/starknet/cheatable_syscall_handler.py
- protostar/testing/cheatcodes/expect_call_cheatcode.py
- tests/integration/cheatcodes/expect_call/expect_call_test.cairo
- tests/integration/cheatcodes/expect_call/expect_call_test.py
- website/docs/tutorials/07-testing/02-cheatcodes/expect-call.md
> Add scope to expect_call cheatcode

- protostar/testing/environments/fuzz_test_execution_environment.py
- protostar/testing/fuzzing/strategy_collector.py
- protostar/testing/fuzzing/strategy_collector_test.py
- tests/integration/fuzzing/fuzzing_test.py
- tests/integration/fuzzing/parameterized_test.cairo
- tests/integration/fuzzing_strategies/one_of_test.cairo
> Remove redundant strategy logic

- protostar/commands/upgrade_command.py
- protostar/upgrader/upgrade_manager.py
Only show `Upgraded successfully` when an upgrade is done
Closes #1097
> Protostar shows upgraded successfully when no upgrade was done #1097

- tests/integration/testing_cache/test_cache.py
Fix a flaky test on the master branch.
> Hotfix — make `TestCache` tests independent

- protostar/cli/signable_command_util.py
> Accept private key as int

- protostar/cli/messenger_factory.py
- website/docs/cli-reference.md
- website/docs/tutorials/08-interacting-with-starknet/01-invoke.md
- website/docs/tutorials/08-interacting-with-starknet/02-call.md
- website/docs/tutorials/08-interacting-with-starknet/03-declare.md
- website/docs/tutorials/08-interacting-with-starknet/04-deploy.md
- website/docs/tutorials/08-interacting-with-starknet/scripting.md
> Add docs for json flag

- protostar/commands/deploy_command.py
- protostar/starknet_gateway/gateway_facade.py
> Fix undeployed account error message

- protostar/commands/deploy_command.py
> deploy_command: tx hash log changed to hex

- website/docs/tutorials/02-installation.md
> Refine docs — installation.md

- protostar/testing/cairo_cheatcodes/cairo_cheatcode.py
- tests/integration/pure_cairo_vm/cheatcodes/deploy/deploy_cairo_cheatcode_test.py
- tests/integration/pure_cairo_vm/cheatcodes/deploy/deploy_test.cairo
- tests/integration/pure_cairo_vm/cheatcodes/deploy_contract/deploy_contract_cairo_cheatcode_test.py
- tests/integration/pure_cairo_vm/cheatcodes/deploy_contract/deploy_contract_test.cairo
Addressing the leftover comments for tests and some nitpick
> New cheatcodes follow up 

- website/docs/tutorials/06-dependencies-management.md
> Refine docs — Dependencies

- website/docs/tutorials/05-compiling.md
> Refine docs — Compiling

- website/docs/tutorials/03-project-initialization.md
- website/docs/tutorials/04-configuration-file.md
> Refine docs — project initialization

- protostar/commands/test/messages/testing_summary_message.py
- protostar/commands/test/test_command.py
- protostar/testing/__init__.py
- protostar/testing/test_collector.py
- protostar/testing/testing_summary.py
- tests/integration/conftest.py
Requested in https://github.com/software-mansion/protostar/pull/1254#discussion_r1046101744
Depends on #1254
> Refactor calculating skipped tests

- protostar/cairo_testing/cairo_test_cheatcode_factory.py
- protostar/cheatable_starknet/cheatable_cached_state.py
- protostar/cheatable_starknet/cheatable_syscall_handler.py
- protostar/cheatable_starknet/cheatcodes/prank_cairo_cheatcode.py
- protostar/cheatable_starknet/cheaters/contracts.py
- tests/integration/pure_cairo_vm/cheatcodes/prank/prank_cairo_cheatcode_test.cairo
- tests/integration/pure_cairo_vm/cheatcodes/prank/prank_cairo_cheatcode_test.py
- tests/integration/pure_cairo_vm/cheatcodes/prank/pranked.cairo
Add prank Cairo Cheatcode.
Closes https://github.com/software-mansion/protostar/issues/1341
> Cairo cheatcode — Prank

- website/docs/tutorials/04-configuration-file.md
> Refine docs — Configuration file

- protostar/cheatable_starknet/cheatables/cheatable_entry_point.py
- protostar/cheatable_starknet/cheatables/cheatable_execute_entry_point.py
- protostar/cheatable_starknet/cheatcodes/call_cairo_cheatcode.py
- protostar/cheatable_starknet/cheatcodes/invoke_cairo_cheatcode.py
- protostar/cheatable_starknet/cheaters/contracts.py
> Remove dead code (cheaters)

- protostar/cairo_testing/cairo_hint_local_factory.py
- protostar/cheatable_starknet/callable_hint_locals/__init__.py
- protostar/cheatable_starknet/callable_hint_locals/roll_hint_local.py
- protostar/cheatable_starknet/callable_hint_locals/stop_roll_hint_local.py
- protostar/cheatable_starknet/callable_hint_locals/stop_warp_hint_local.py
- protostar/cheatable_starknet/callable_hint_locals/warp_hint_local.py
- protostar/cheatable_starknet/controllers/block_info.py
- tests/integration/pure_cairo_vm/cheatcodes/stop_roll/stop_roll_cairo_cheatcode_test.py
- tests/integration/pure_cairo_vm/cheatcodes/stop_roll/stop_roll_test.cairo
- tests/integration/pure_cairo_vm/cheatcodes/stop_warp/stop_warp_cairo_cheatcode_test.py
- tests/integration/pure_cairo_vm/cheatcodes/stop_warp/stop_warp_test.cairo
> `stop_warp` & `stop_roll` cheatcodes

- protostar/cairo_testing/cairo_hint_local_factory.py
- protostar/cheatable_starknet/callable_hint_locals/call_hint_local.py
- protostar/cheatable_starknet/callable_hint_locals/callable_hint_local.py
- protostar/cheatable_starknet/callable_hint_locals/declare_hint_local.py
- protostar/cheatable_starknet/callable_hint_locals/deploy_hint_local.py
- protostar/cheatable_starknet/callable_hint_locals/expect_events_cairo_cheatcode.py
- protostar/cheatable_starknet/callable_hint_locals/invoke_hint_local.py
- protostar/cheatable_starknet/callable_hint_locals/load_hint_local.py
- protostar/cheatable_starknet/callable_hint_locals/prank_hint_local.py
- protostar/cheatable_starknet/callable_hint_locals/prepare_hint_local.py
- protostar/cheatable_starknet/callable_hint_locals/roll_hint_local.py
- protostar/cheatable_starknet/callable_hint_locals/stop_roll_hint_local.py
- protostar/cheatable_starknet/callable_hint_locals/stop_warp_hint_local.py
- protostar/cheatable_starknet/callable_hint_locals/store_hint_local.py
- protostar/cheatable_starknet/callable_hint_locals/warp_hint_local.py
- protostar/cheatable_starknet/controllers/__init__.py
> Stop using shared `Controllers` for hint locals

- protostar/cairo_testing/cairo_hint_local_factory.py
- protostar/cheatable_starknet/callable_hint_locals/__init__.py
- protostar/cheatable_starknet/callable_hint_locals/callable_hint_local.py
- protostar/cheatable_starknet/callable_hint_locals/mock_call_hint_local.py
- protostar/cheatable_starknet/cheatables/cheatable_cached_state.py
- protostar/cheatable_starknet/cheatables/cheatable_syscall_handler.py
- protostar/cheatable_starknet/controllers/contracts.py
- protostar/starknet/selector.py
- tests/integration/pure_cairo_vm/cheatcodes/mock_call/mock_call_hint_local_test.cairo
- tests/integration/pure_cairo_vm/cheatcodes/mock_call/mock_call_hint_local_test.py
- tests/integration/pure_cairo_vm/contracts/number_provider_contract.cairo
- tests/integration/pure_cairo_vm/contracts/number_provider_proxy.cairo
Closes https://github.com/software-mansion/protostar/issues/1346
> Add `mock call` hint local

- protostar/cairo_testing/cairo_hint_local_factory.py
- protostar/cheatable_starknet/callable_hint_locals/__init__.py
- protostar/cheatable_starknet/callable_hint_locals/assert_expect_call_hint_local.py
- protostar/cheatable_starknet/callable_hint_locals/stop_expect_call_hint_local.py
- protostar/cheatable_starknet/controllers/expect_call_controller.py
- tests/integration/cairo1_compiler_bindings/tests_collector_and_compiler_test.py
- tests/integration/pure_cairo_vm/cheatcodes/expect_call/expect_call_cairo_cheatcode_test.py
- tests/integration/pure_cairo_vm/cheatcodes/expect_call/expect_call_test.cairo
> Add assert expect call hint local

- protostar/cairo/cairo_bindings.py
- scripts/install_cairo_bindings.sh
Depends on https://github.com/software-mansion-labs/cairo/pull/22 and until that one's merged, the CI's going to fail here.
> Update bindings' names

- protostar/starknet_gateway/gateway_facade.py
> Display more informative error message when account is not deployed (declare command)

- README.md
- pyproject.toml
- scripts/bump_cairo_bindings.sh
- scripts/install_cairo_bindings.sh
Closes https://github.com/software-mansion/protostar/issues/1556
> Separate updating bindings and installation

- tests/integration/cairo1_compiler_bindings/library_functions_test.py
- tests/integration/cairo1_compiler_bindings/library_functions_test/mock_call_test.cairo
Related cairo PR https://github.com/software-mansion-labs/cairo/pull/25
> Add mock_call lib function test

- protostar/cairo/cairo_bindings.py
- tests/e2e/fixtures/cairo1_project/tests/test_a.cairo
- tests/e2e/fixtures/cairo1_project/tests/test_with_deps.cairo
- tests/integration/cairo1_compiler_bindings/test_typecheck_test.py
- tests/integration/cairo1_compiler_bindings/test_typecheck_test/test_basic.cairo
- tests/integration/cairo1_compiler_bindings/test_typecheck_test/test_with_args.cairo
- tests/integration/cairo1_compiler_bindings/test_typecheck_test/test_with_no_panic.cairo
- tests/integration/cairo1_compiler_bindings/test_typecheck_test/test_with_ret_vals.cairo
- tests/integration/cairo1_compiler_bindings/test_typecheck_test/test_without_panic.cairo
- tests/integration/cairo1_compiler_bindings/tests_collector_and_compiler_test/test_with_deps.cairo
- tests/integration/pure_cairo_vm/cairo1_integration/cairo1_runner_test/multiple_suites/test_cairo1.cairo
- tests/integration/pure_cairo_vm/cairo1_integration/cairo1_runner_test/multiple_suites/test_cairo1_two_cases.cairo
- tests/integration/pure_cairo_vm/cairo1_integration/cairo1_runner_test/test_cairo1.cairo
- tests/integration/pure_cairo_vm/cairo1_integration/cairo1_runner_test/test_cairo1_ext_lib.cairo
- tests/integration/pure_cairo_vm/cairo1_integration/cairo1_runner_test/test_cairo1_two_cases.cairo
https://github.com/software-mansion-labs/cairo/pull/26
> Cairo1 test typecheck test

- website/docs/tutorials/08-cairo-1-support/01-project-initialization.md
> Add docs about cairo 1 modules

- tests/integration/_conftest/protostar_fixture_factory.py
- tests/integration/pure_cairo_vm/cairo1_integration/cairo1_runner_test.py
+ remove create_files in cairo1_runner_test
https://github.com/software-mansion/protostar/issues/1580
> Use LinkedLibrariesBuilder in create_protostar_fixture when creating TestCommand

- protostar/testing/environments/fuzz_test_execution_environment.py
- tests/integration/fuzzing/fuzzing_test.py
- tests/integration/fuzzing/parameterized_test.cairo
We had not been waiting for async test function to execute.
> Fix the example cheatcode

- .github/workflows/build_docs.yml
- .github/workflows/builds_on_mac.yml
- .github/workflows/checks.yml
Let's decide internally if we want to enable merge queue, before merging this.
> Add `merge_group` event trigger for essential checks

- protostar/cairo/cairo_bindings.py
- protostar/cairo/cairo_function_runner_facade.py
- tests/integration/cairo1/builtins_test/test.cairo
- tests/integration/cairo1_compiler_bindings/library_functions_test.py
- tests/integration/cairo1_compiler_bindings/library_functions_test/deploy_test.cairo
Blocking cairo PR https://github.com/software-mansion-labs/cairo/pull/44
> Fix builtins

- tests/integration/cairo1_compiler_bindings/library_functions_test.py
- tests/integration/cairo1_compiler_bindings/library_functions_test/call_test.cairo
cairo related PR https://github.com/software-mansion-labs/cairo/pull/50
> Add cairo1 call

- tests/integration/cairo1_compiler_bindings/library_functions_test.py
- tests/integration/cairo1_compiler_bindings/library_functions_test/call_test.cairo
- tests/integration/cairo1_compiler_bindings/library_functions_test/declare_cairo0_test.cairo
- tests/integration/cairo1_compiler_bindings/library_functions_test/declare_test.cairo
- tests/integration/cairo1_compiler_bindings/library_functions_test/deploy_test.cairo
- tests/integration/cairo1_compiler_bindings/library_functions_test/prepare_test.cairo
This is built on the top of https://github.com/software-mansion/protostar/pull/1682
Related Cairo PR https://github.com/software-mansion-labs/cairo/pull/51
> Check cheatcodes return values

- tests/integration/cairo1_compiler_bindings/library_functions_test.py
Depends on https://github.com/software-mansion-labs/cairo/pull/53
> Adjust prepare tests 

- tests/integration/cairo1_compiler_bindings/library_functions_test.py
- tests/integration/cairo1_compiler_bindings/library_functions_test/deploy_contract_test.cairo
> Add a test for `deploy_contract`

- protostar/cairo/cairo_bindings.py
- tests/integration/cairo1_compiler_bindings/starknet_contracts_compiler_test.py
Cairo PR https://github.com/software-mansion-labs/cairo/pull/61
> Add tests for sierra -> casm compilation

- website/docs/tutorials/08-cairo-1-support/03-cheatcodes/declare-cairo0.md
- website/docs/tutorials/08-cairo-1-support/03-cheatcodes/declare.md
> Update declare and declare-cairo0 docs

- protostar/commands/cairo1_commands/build_cairo1_command.py
- tests/e2e/cairo1/test_cairo1_building.py
- tests/e2e/cairo_0_1_mixed/test_cairo_0_1_mixed_building.py
closes https://github.com/software-mansion/protostar/issues/1684
> Produce both sierra and casm outputs when build-cairo1

- website/docs/tutorials/08-cairo-1-support/03-testing.md
> Fix misleading cairo1 docs

- protostar/commands/init/project_creator/new_project_creator.py
- tests/e2e/cairo1/test_cairo1_init.py
> Add tests to cairo1 project creation logic

- protostar/cairo/cairo_bindings.py
- protostar/cairo/cairo_exceptions.py
- protostar/commands/cairo1_commands/build_cairo1_command.py
- protostar/compiler/project_compiler.py
- protostar/testing/test_collector.py
- tests/integration/cairo1/compiler_bindings/test_typecheck_test.py
> 1820 nicer exceptions
