software-mansion/protostar

.github/workflows/build_binaries.yml

Python 3.7.12 doesn't support ARM architecture, which probably caused the following error:
`zsh: bad CPU type in executable: protostar`

Use Python 3.8 in the build process

---

src/commands/install/pull_package_submodules.py
src/commands/install/pull_package_submodules_test.py

```
19:24:41 [INFO] Installing cairo_integer_types (https://github.com/bellissimogiorno/cairo-integer-types)
19:24:42 [WARNING] Failed to checkout tracking branch refs/heads/master
19:24:42 [INFO] Installing cairo_contracts (https://github.com/OpenZeppelin/cairo-contracts)
19:24:44 [WARNING] Failed to checkout tracking branch refs/heads/master
19:24:44 [INFO] Skipping reset on branch 'HEAD' of submodule repo '<git.repo.base.Repo '/Users/timelock/swm/starkware/access-protocol-starknet/.git/modules/cairo_contracts'>' as it contains un-pushed commits
```
https://github.com/gitpython-developers/GitPython/issues/1058

Fix installing a package without master branch

---

protostar.py
src/cli.py
src/commands/test/collector.py
src/commands/test/collector_test.py
src/commands/test/examples/nested/test_basic.cairo
src/commands/test/runner.py

Changes:
- support of a syntax `a/b/c.cairo`
- support of a syntax `a/b/c.cairo::test_function`
- some refactoring
- now match and omit regexes refer to filenames not whole paths
Docs update task:
https://github.com/software-mansion/protostar/issues/133#issue-1191402912

Test runner improved

---

src/commands/test/runner.py
src/utils/starknet_compilation.py
tests/e2e/test_testing.py

- fixed Unknown location
```
Cairo traceback (most recent call last):
Unknown location (pc=0:5042)
Unknown location (pc=0:5035)
Unknown location (pc=0:4484)
Unknown location (pc=0:4265)
Unknown location (pc=0:2090)
```

Enable debug info for tests

---

website/docs/tutorials/guides/testing.md

Currently, deployed docs describe the updated `start_prank`.

Bring back old start_prank docs

---

protostar/commands/test/test_collector.py
protostar/commands/test/test_collector_test.py
protostar/commands/test/test_runner.py
protostar/commands/test/test_suite.py
protostar/utils/starknet_compilation.py
tests/integration/testing_hooks/testing_hooks_test.cairo
tests/integration/testing_hooks/testing_hooks_test.py

- added skipping integration test for the feature
- made Protostar raise `NotImplementedError` if `setup_state` is detected
- discovered bug https://github.com/software-mansion/protostar/issues/308

[`setup_state`::01]  Detect and try executing hook

---

protostar/commands/test/test_collector.py
protostar/commands/test/test_collector_test.py
protostar/commands/test/test_suite.py

Extended `TestCollector` to search and ignore, `test_suites` and `test_cases` by globs.
(This PR doesn't change the test command's interface.)
--- 
1. map `test_suite_glob::test_case_glob` to `List[test_suite_path::test_case_glob]` for `target` and `ignore`
2. combine `test_case_globs` in `Mapping[test_case_path, Set[test_case_glob]]` for `target` and `ignore`
3. subtract from target ignored paths
4. build `TestSuite` from target and ignored test case globs for the specific test suite
5. ...

[globs::01] Add `collect_from_globs` method to `TestCollector`

---

protostar/commands/test/cheatcodes/deploy_cheatcode.py
protostar/commands/test/starkware/cheatable_execute_entry_point.py

This problem was caused by using multiple syscall handlers (each cheatcode inherit from `SyscallHandler`), what eventually broke Starknet's code.

Fix `list assignment index out of range`

---

protostar/commands/test/test_command.py
protostar/commands/test/testing_live_logger.py
protostar/protostar_cli.py
website/docs/cli-reference.md

I didn't use `TERM` env variable because mapping `TERM` value to the useful information is not trivial. I'd probably need to use `terminfo` database and there are more important tasks to do.

Allow disabling progress bar

---

protostar/commands/test/test_context.py
protostar/commands/test/test_context_test.py
tests/integration/cheatcodes/deploy_contract/deploy_contract_test.cairo
tests/integration/testing_hooks/invalid_setup_test.cairo
website/docs/tutorials/guides/testing.md

Previously, `DeployedContract` stored in the `TestContext` froze Protostar, hence the restriction was added. Currently, `DeployedContract` doesn't store a reference to starknet and it can be stored in the context.

Remove test context type restriction

---

protostar/commands/test/test_command.py
protostar/commands/test/testing_live_logger.py
tests/e2e/test_testing.py
website/docs/cli-reference.md

I'd like to keep optional printing functionality within the TestCaseResult class, as it is something that may be needed later.

Removed --stdout-on-success flag, made printing default behaviour

---

protostar/commands/test/cheatcodes/declare_cheatcode.py
protostar/starknet/cheatcode.py
protostar/starknet/forkable_starknet.py
tests/integration/cheatcodes/expect_events/expect_events_test.cairo
tests/integration/cheatcodes/expect_events/expect_events_test.py

Adding ABI in a constructor causes issues in Migration cheatcodes.
This PR was merged too fast:
https://github.com/software-mansion/protostar/pull/496

Refactor fix for data transformer in `expect_events`

---

tests/integration/conftest.py

This little PR makes debugging integration tests much more pleasant, by doing single assert statement which checks all test case sets at once, and emitting a diff-friendly representation.
Additionally, this PR adds an ability to check broken test cases.

Improve assert_cairo_test_cases diffing

---

protostar/commands/test/environments/fuzz_test_execution_environment.py
tests/integration/fuzzing/fuzzing_test.py
tests/integration/fuzzing/hypothesis_multiple_errors_test.cairo

This PR sets `report_multiple_bugs` Hypothesis setting to `False` in order to prevent it from raising a problematic`hypothesis.errors.MultipleFailures` exception. In the future we might consider reenabling this setting again and somehow trying to infer all the failures, but as for now IMHO reporting single error is helpful enough.
fix #528

Avoid `hypothesis.errors.MultipleFailures` exception

---

protostar/commands/test/environments/fuzz_test_execution_environment.py
tests/integration/fuzzing/fuzzing_test.py

This info was calculated under the assumption that `fuzz_runs` is equal to `fuzz_max_examples` which is not the case.

Remove fuzz simplification runs info 

---

.github/ISSUE_TEMPLATE/bug_report.md

Personally, I find this prefix noisy, as we already have the very shouty red `bug` label. Wdyt?

Remove the [BUG] prefix from issue template

---

tests/e2e/conftest.py

fix copy_fixture typing to accept str as arguments

---

protostar/commands/test/test_collector.py
protostar/commands/test/test_collector_test.py
protostar/commands/test/test_suite.py

This PR adds support for collecting `setup_*` cases in `TestCollector`. Nothing else is done with these yet.

Collect setup cases

---

README.md
install.sh
website/docs/tutorials/02-installation.md

Adds option `-v` to install script, in the lack of if, it will install latest version.
On specifying a non existent version, it will fail gracefully:
```bash
$ ./install.sh -v 0.3.33
Installing protostar
Retrieving 0.3.33 version from https://github.com/software-mansion/protostar...
Version 0.3.33 not found
```
Fixes #570 #638

Add option to specify install version

---

protostar/commands/test/test_case_runners/test_case_runner_factory.py
protostar/commands/test/test_runner.py

This change allows calling future setup case running logic from TestRunner.

Fork test execution state in TestRunner

---

protostar/commands/test/test_case_runners/fuzz_test_case_runner.py
protostar/commands/test/test_environment_exceptions.py
protostar/commands/test/test_environment_exceptions_test.py

Small change which increases code robustness in case new metadata types are added.

Add `ReportedException.get_metadata_by_type`

---

protostar/commands/test/cheatcodes/__init__.py
protostar/commands/test/cheatcodes/deploy_contract_cheatcode.py
protostar/commands/test/environments/setup_execution_environment.py

This fixed "unused import" errors reported by PyCharm in `__init__.py`.

Import cheatcodes from grouping module wherever possible

---

tests/e2e/installation_script/conftest.py
tests/e2e/installation_script/test_install_sh.py

Flaky test was caused by a race condition (`simulate_unwrapping` vs `chmod`)

Fix flaky test and rename fixture

---

protostar/commands/test/cheatcodes/reflect/cairo_struct_test.py

This PR workarounds this error which pops for me from time to time.
```
************* Module protostar.commands.test.cheatcodes.reflect.cairo_struct_test
protostar/commands/test/cheatcodes/reflect/cairo_struct_test.py:50:8: C0103: Attribute name "b" doesn't conform to snake_case naming style (invalid-name)
```
Personally I would disable this inspection.

Silence Pylint error

---

protostar/commands/test/environments/test_execution_environment.py
protostar/commands/test/starkware/test_execution_state.py
protostar/commands/test/test_case_runners/test_case_runner_factory.py
protostar/commands/test/test_config.py
protostar/commands/test/test_config_test.py
protostar/commands/test/test_runner.py

This PR cleans up the logic for inferring test mode from test case function signature. I have decided to leave the behaviour so that we won't break existing fuzz tests in users' projects, i.e. this will still work:
```cairo
@external
def test_foo(a):
...
end
```
I am unsure about adding the `TestMode.UNDETERMINED` variant. My rationale behind this was to mark explicitly cases when inference is *needed*, instead of making a wild assumption that `TestMode.STANDARD` means this (who knows if we someday introduce a unit test specific cheatcode). Correct me if I'm wrong 😀
This is the last PR before submitting fuzzing strategies API rework. That PR will use the `convert_mode_to` method added to `TestConfig`

Clean up test mode determination logic

---

protostar/commands/test/test_scheduler.py

This PR fixes a bug that has been surfaced while upgrading Python to version 3.9. Lambdas are not pickleable. Only top-level functions are.
cc #697

Avoid using lambdas in `multiprocessing.Pool` `initializer` argument

---

protostar/commands/test/cheatcodes/expect_events_cheatcode.py
protostar/commands/test/expected_event.py
website/docs/tutorials/07-testing/02-cheatcodes/expect-events.md

Just found an opportunity here to clean up things.

Simplify types around `expect_events` cheatcode

---

binary_entrypoint.py
tests/e2e/conftest.py
tests/e2e/test_building.py
tests/e2e/test_misc_commands.py
tests/e2e/test_testing.py

The only failing tests left are the devnet-dependent ones.
fixes #798

Improve crash reporting in E2E tests and fix failing ones

---

protostar/configuration_file/configuration_file.py
protostar/configuration_file/configuration_file_v1.py
protostar/configuration_file/configuration_file_v1_test.py
protostar/configuration_file/configuration_file_v2.py
protostar/configuration_file/configuration_file_v2_test.py
protostar/self/__init__.py
protostar/self/protostar_compatibility_with_project_checker.py
protostar/self/protostar_compatibility_with_project_checker_test.py

Currently, `protostar_version` is not properly handled by Protostar. It shouldn't be used to detect the version of the configuration file (v1, v2), but help a development team that uses Protostar to use compatible versions.
Let's say we introduce a new cheatcode in Protostar v0.5. Alice upgraded Protostar and uses Protostar v0.5. Bob uses Protostar v0.4. Alice uses the new cheatcode and integrates her code with the mainline. Bob pulls the mainline and runs the code that uses the new cheatcode.
We should bump the minor (not micro) if forward compatibility is no preserved (e.g. new cheatcode).
Protostar crashes for Bob. 
1. Protostar tells Alice to update the declared version in the configuration file.
2. Protostar tells Bob to upgrade Protostar.

Redesigning `protostar.toml` 6 — Version checker

---

protostar/configuration_file/configuration_file_factory.py
protostar/configuration_file/configuration_file_factory_test.py
protostar/configuration_file/configuration_file_v2.py
protostar/configuration_file/configuration_file_v2_test.py
protostar/configuration_file/configuration_legacy_toml_interpreter.py
protostar/configuration_file/configuration_toml_interpreter.py
tests/conftest.py

`ConfigurationFileFactory` builds the proper version of the `ConfigurationFile`.
This PR doesn't change the Protostar logic yet. I'll merge this PR without review on 27 September at 3 pm.

Redesigning `protostar.toml` 7 — `ConfigurationFileFactory`

---

protostar/profiler/contract_profiler.py
protostar/profiler/contract_profiler_test.py
protostar/profiler/pprof.py
protostar/profiler/profile.py
protostar/starknet/cheatable_execute_entry_point.py

Transaction profiler will be refactored in a separeate PR. 
This PR adds:
- some docstring
- some structure simplifications
- improves typing
- adds some test for functions which are unit-testable
I will add general integration tests after I integrate profiler in the final way (we discussed this integration with @kasperski95), right now those are a litlle too difficult to setup.
#828

Refactor of contract profiler

---

protostar/commands/migrate_configuration_file_command.py
protostar/configuration_file/__init__.py
protostar/configuration_file/configuration_file.py
protostar/configuration_file/configuration_file_factory.py
protostar/configuration_file/configuration_file_factory_test.py
protostar/configuration_file/configuration_file_v1.py
protostar/configuration_file/configuration_file_v1_test.py
protostar/configuration_file/configuration_file_v2.py
protostar/configuration_file/configuration_file_v2_migrator.py
protostar/configuration_file/configuration_file_v2_migrator_test.py
protostar/configuration_file/configuration_file_v2_test.py
protostar/configuration_file/configuration_toml_content_builder.py
protostar/configuration_file/configuration_toml_content_builder_test.py
protostar/configuration_file/conftest.py
protostar/self/__init__.py
protostar/self/conftest.py
protostar/self/protostar_compatibility_with_project_checker_test.py

This PR adds Configuration File Migrator and corresponding command. The command isn't visible to the user yet.

Redesigning `protostar.toml` 9 — Migrator

---

protostar/utils/protostar_directory.py

This PR allows developers to run Protostar without building it e.g.
```
python ./binary_entrypoint.py --help
```

Don't panic when `constants.json` doesn't exist

---

website/docs/tutorials/07-testing/02-cheatcodes/send-message-to-l2.md

This PR applies minor fixups in `send_message_to_l2` docs:
1. Reformatted cheatcode signature with Black,
2. `l1, l2` → `L1, L2` to match Starknet's spelling.

Reformat & fix typos in `send_message_to_l2` docs

---

protostar/testing/cheatcodes/deploy_cheatcode.py
protostar/testing/cheatcodes/prepare_cheatcode.py
tests/integration/cheatcodes/deploy_contract/deploy_contract_test.py
tests/integration/cheatcodes/deploy_contract/deploying_contract_with_incorrect_args_test.cairo

This PR adds some parsing of the arguments and catching the exceptions, in order to produce more user-friendly way of reporting constructor argument errors.
fixes #912

Make `deploy_contract` constructor call errors more user-friendly

---

website/docs/tutorials/07-testing/02-cheatcodes/example.md
website/docs/tutorials/07-testing/02-cheatcodes/given.md
website/docs/tutorials/07-testing/02-cheatcodes/max-examples.md

I find these warning boxes to be misleading, as there is no danger here. We only want users to pay attention.

Do not lit a fire so much in some cheatcodes docs

---

website/src/theme/DocPage/Layout/Main/index.js

Fix stale comment box after navigating to a different page and change the mapping method to `pathname` (`title` mapping didn't work and `url` was too verbose).

Hot-fix stale comments

---

protostar/cli/network_command_util.py
protostar/cli/network_command_util_test.py

Show supported chain ID values if invalid is provided. Supported values are hard to memorize. A user needs to provide chain ID explicitly when using Protostar with devnet.
Closes #1074

Suggest chain-ids values

---

protostar/cli/__init__.py
protostar/cli/common_arguments.py
protostar/cli/lib_path_resolver.py
protostar/cli/lib_path_resolver_test.py
protostar/commands/install/install_command.py
protostar/commands/remove/remove_command.py
protostar/commands/update/update_command.py
protostar/compiler/project_cairo_path_builder.py
protostar/composition_root.py
tests/integration/protostar_fixture.py
website/docs/cli-reference.md

Add `lib-path` argument to package management commands. This argument is used after migrating to the `ConfigurationFileV2`. Make lib directory optional.
Related #477

Redesigning `protostar.toml` 13 — Rolling integration — Package management commands

---

protostar/commands/migrate_command.py
protostar/commands/migrate_command_test.py
protostar/migrator/migrator.py
tests/integration/migrator/migrator_test.py
tests/integration/protostar_fixture.py
website/docs/cli-reference.md
website/docs/tutorials/06-deploying/02-migrations/README.md

Remove rollback functionality from migrations. This functionality creates more confusion than good.
Related #1001

Remove rollback from migrations

---

protostar/cli/network_command_util.py
protostar/cli/protostar_arg_type.py
protostar/cli/protostar_arg_type_test.py
protostar/cli/signable_command_util.py
protostar/commands/__init__.py
protostar/commands/deploy_account_command.py
protostar/composition_root.py
tests/_conftest/devnet/devnet_fixture.py
tests/e2e/test_gateway_commands.py
tests/integration/commands/deploy_account_command_test.py
tests/integration/commands/invoke_command_test.py
tests/integration/gateway/gateway_facade_test.py
tests/integration/protostar_fixture.py
website/docs/cli-reference.md

Allow sending "deploy account" transactions from the CLI.
Related #962. Docs will be added in another PR.

Add `deploy-account` command

---

protostar/commands/migrate_configuration_file_command.py
protostar/composition_root.py
protostar/configuration_profile_cli.py
protostar/protostar_cli.py
protostar/protostar_cli_test.py
tests/e2e/test_misc_commands.py
website/docs/cli-reference.md

Allow migrating configuration files. Show depreciation warning. Add E2E test.
Related #477

Redesigning `protostar.toml` 17 — Connect `migrate-configuration-file` command

---

protostar/migrator/migrator_cheatcodes_factory.py
protostar/starknet/cheatable_execute_entry_point.py
protostar/starknet/cheatcode.py
protostar/starknet/cheatcode_factory.py
protostar/testing/cheatcodes/deploy_cheatcode.py
protostar/testing/environments/common_test_cheatcode_factory.py
protostar/testing/environments/fuzz_test_execution_environment.py
protostar/testing/environments/setup_case_execution_environment.py
protostar/testing/environments/setup_execution_environment.py
protostar/testing/environments/test_execution_environment.py
tests/integration/cheatcodes/send_message_to_l2/external_contract_with_l1_handler.cairo
tests/integration/cheatcodes/send_message_to_l2/send_message_to_l2_test.py
tests/integration/cheatcodes/send_message_to_l2/simple_l1_handler_test.cairo

Fix crash caused by `send_message_to_l2` cheatcode. Fix the problem in the `Cheatcode` class to avoid reintroducing this problem by new cheatcodes.
Fixes #1065

Make all cheatcodes use one shared `internal_calls`. Fix `send_message_to_l2` cheatcode.

---

protostar/cli/network_command_util.py
protostar/cli/network_command_util_test.py
protostar/commands/deploy_command.py
protostar/starknet_gateway/network_config.py
protostar/starknet_gateway/network_config_test.py
website/docs/cli-reference.md

Remove already deprecated names like `alpha-goerli` to make the block explorer links creator simpler (https://github.com/software-mansion/protostar/pull/1122).

Remove legacy network names

---

website/docs/tutorials/07-testing/03-fuzzing/README.md
website/docs/tutorials/08-interacting-with-starknet/01-invoke.md
website/docs/tutorials/08-interacting-with-starknet/02-call.md

commit-id:6d2060cc
---
**Stack**:
- #1132
- #1137
- #1134
- #1131
- #1136
- #1135 ⬅

Remove unnecessary execution time logs from documentation

---

.pylintrc

As requested [here](https://github.com/software-mansion/protostar/pull/1140#discussion_r1021324991), I'm moving this to a new PR.
We decided that the lint rule `max-returns` is not that good and can be removed.

Remove max returns

---

.pylintrc
protostar/argument_parser/argument_parser_facade.py
protostar/argument_parser/argument_parser_facade_test.py

Replace dashes with underscores in the parsing result. Argparse doesn't do that for some reason. Disabled pylint's no-member rule due to false positives.
https://bugs.python.org/issue15125
Related https://github.com/software-mansion/protostar/pull/1168

Fix kebab-case with positional arguments

---

protostar/argument_parser/arg_type.py
protostar/argument_parser/arg_type_test.py
protostar/argument_parser/argument.py
protostar/argument_parser/argument_parser_facade.py
protostar/argument_parser/argument_parser_facade_test.py
protostar/argument_parser/conftest.py
protostar/argument_parser/unparser.py
protostar/argument_parser/unparser_test.py

Run type parsers on arguments from configuration file. Argparse runs parsers on default values only if they are strings.
Closes #1178

Fix parsing non-string values from configuration file

---

protostar/configuration_file/argument_value_resolver.py
protostar/configuration_file/component_test.py

Fix loading shared argument from the `[project]` section, when `profile` is provided.
Fixes #1181

Fix loading shared args when profile is provided

---

tests/integration/conftest.py

Removes `empty_protostar_toml` fixture. It created a corrupted file in the project root directory, which was causes nondeterministic failures of CLI reference docs snapshot test. The CLI reference docs test fails, because it uses the `ProtostarCLI` build in the composition root to ensure that documentation matches the CLI. The composition root loads the configuration file because Marek didn't like lazy loading. 
Flaky test example:
https://github.com/software-mansion/protostar/actions/runs/3674857449/jobs/6213618607

Fix flaky test (`empty_protostar_toml` fixture)

---

pyproject.toml

This reverts commit 26274f79283d671401a2031214710b2e362a3945. https://github.com/software-mansion/protostar/pull/1272 should fix the action.

Revert commit "release Protostar 0.9.0" (release failed)

---

tests/conftest.py
tests/e2e/conftest.py
tests/integration/conftest.py

Hotfix CI freezes — Use `module` scope for devnet fixture

---

protostar/starknet/data_transformer.py
tests/integration/data_transformer/contracts.py
tests/integration/data_transformer/data_transformer_test.py

The point is to prevent people from using `felt*` for passing `dict`s like this:
```
%{ ids.proxy_contract_address = deploy_contract("./ctr.cairo", {"d": {"a": 1, "b": 3}}).contract_address %}
// ctr.cairo
func constructor{syscall_ptr: felt*, pedersen_ptr: HashBuiltin*, range_check_ptr}(d_len: felt, d: felt*) {
%{
from starkware.cairo.lang.vm.relocatable import RelocatableValue
rel = RelocatableValue.to_felt_or_relocatable(ids.d)
values = [memory[rel+i] for i in range(0, ids.d_len)]
print("length", ids.d_len)
print("values", values) # that's going to give you only the keys and will cause a data loss
%}
return ();
}
```
fix #1266

Prevent using felt pointer for dict

---

.pylintrc
binary_entrypoint.py
docs_generator/reference_docs_generator.py
protostar/starknet/compiler/cairo_compilation.py
protostar/starknet/compiler/pass_managers.py
pyproject.toml
tests/conftest.py
tests/e2e/conftest.py
tests/e2e/test_building.py
tests/e2e/test_formatting.py
tests/e2e/test_fuzzing.py
tests/e2e/test_misc_commands.py
tests/integration/cheatcodes/expect_call/expect_call_test.py
tests/integration/commands/call_command_test.py
tests/integration/compilation/starknet_compilation_test.py
tests/integration/compilation/test_case_compiler_test.py
tests/integration/fuzzing_strategies/fuzzing_strategies_test.py
tests/integration/gateway/gateway_facade_test.py
tests/integration/gateway/uint256_as_input_test.py
tests/integration/protostar_fixture.py
tests/integration/testing_cache/test_cache.py
tests/integration/testing_timing/testing_timing_test.py

Check linting for every Python file in the project. Disabled unspecified-encoding rule. Currently, the linting checks only the files in the Protostar directory.
---
> Missing timeout argument for method ‘requests.get’ can cause your program to hang indefinitely
Maybe this is why CI kept freezing?

Lint everything

---

pyproject.toml

Set `black` profile in the `isort` configuration. It fixes the racing condition between black formatter and sort organizer in VS Code. This setting was accidentally removed in PR that disabled alphabetical imports.

Bring back black profile to isort

---

install.sh

Docker Alpine images come with ash as the default shell instead of bash.
The support of the ash shell would allow using docker containers such as ```python:3.9-alpine``` allowing a quick setup for the Cairo env.

fix(install): support ash shell

---

.pylintrc
protostar/commands/test/test_command.py
protostar/commands/test/testing_live_logger.py
protostar/testing/test_scheduler.py

Break cyclic imports caused by `protostar.testing` component importing from `protostar.commands`. 
For some reason, Pylint started complaining when I changed the os from the `ubuntu-latest` to `ubuntu-20.04` in this PR https://github.com/software-mansion/protostar/actions/runs/3911262001/jobs/6685094177.

Break cyclic imports (`protostar.testing` importing from `protostar.commands`)

---

.github/workflows/assign_issues_to_project.yml
.github/workflows/assign_pr_author.yml
.github/workflows/assign_size_label.yml
.github/workflows/build_binaries.yml
.github/workflows/build_docs.yml
.github/workflows/checks.yml
.github/workflows/deploy_docs.yml
.github/workflows/test_installation.yml
.pylintrc
tests/e2e/test_upgrading.py

Use Ubuntu 20.04 to build binaries. [Protostar v0.8.1](https://github.com/BibliothecaDAO/realms-contracts/issues/270) doesn't have this problem. [Recently, `ubuntu-latest` was updated to use Ubuntu 22.04.](https://github.com/actions/runner-images/issues/6399)
> You're better off finding a Python built with a lower glibc requirement which in practice means building on an old version of Linux or an old docker image.
https://github.com/pyinstaller/pyinstaller/discussions/5669
Probably Fixes #1293

Fix GLIBC issue

---

tests/integration/conftest.py
tests/integration/conftest_test.py

Improve 'assert_cairo_test_cases' feedback. `CairoCheatcodes` cairo tests can't be run with Protostar in the console. Checking test results with a debugger is annoying.
Before:
After:

Improve `assert_cairo_test_cases`' feedback

---

protostar/commands/install/install_package_from_repo.py
protostar/commands/install/install_package_from_repo_test.py
protostar/git/git_helpers.py
protostar/git/git_helpers_test.py
protostar/git/git_repository.py
protostar/git/git_repository_test.py

Make git errors more descriptive. Don't crash when committing unstaged files.
Closes: https://github.com/software-mansion/protostar/issues/1290
Before:
After (but before fixing this concrete problem):

Make git error message more descriptive

---

.github/workflows/build_binaries.yml
.github/workflows/builds_on_mac.yml
.github/workflows/checks.yml

_"Whatever method you use, it is highly recommended to explicitly control the version of Poetry used, so that you are able to upgrade after performing your own validation."_
Source: https://python-poetry.org/docs/master/#ci-recommendations
Related issue on CI:
https://github.com/software-mansion/protostar/actions/runs/4292622238/jobs/7479310114

Set fixed poetry version to 1.3.2 in all Actions

---

protostar/starknet/starknet_compiler.py

I don't see a gain in excluding one line of code into a separate function if it's going to be called just once.

Flatten code in compiler

---

scripts/install_cairo_bindings.sh

Cairo 1 own CI uses specific nightly version https://github.com/software-mansion-labs/cairo/blob/a373e713b4eb306eb091970de1a1a9644e10fc12/.github/workflows/ci.yml#L77
We should use the same version in our scripts instead of pulling the latest release which can contain problems.

Set rust version to `nightly-2022-11-03` in `install_cairo_bindings.sh`

---

protostar/cairo/cairo_bindings.py

I discovered that there are errors that are thrown from rust and are not `RuntimeError`. The result was, in my case, an infinite hang which is very bad. The error was something like `pyo3_runtime.PanicException`. Are there any objections to just catching everything that comes from rust (I mean errors) and turning it into `CairoBindingException`?

Change scope of errors reraised in bindings

---

tests/conftest.py
tests/integration/conftest.py
tests/integration/deploying/declare_command_test.py
tests/integration/deploying/deploy_command_test.py
tests/integration/gateway/uint256_as_input_test.py

This is pretty brute-force, i'll explain what it does and why:
`tmp_path` and `tmp_path_factory` are not actually deleted after a test case/module/test session run.
This causes to clog up the disk and fail our CI
- reduce scope of some protostar-fixtures to function, to keep things contain and easy to manage from fixture
- wraps pytests fixures into our own, which are deleted after a case run

`tmp_path` fixtures wrappers

---

protostar/cheatable_starknet/callable_hint_locals/deploy_hint_local.py
protostar/cheatable_starknet/callable_hint_locals/prepare_hint_local.py
scripts/install_cairo_bindings.sh
tests/integration/cairo1/compiler_bindings/library_functions_test.py
tests/integration/cairo1/compiler_bindings/library_functions_test/deploy_test.cairo
tests/integration/cairo1/compiler_bindings/library_functions_test/prepare_test.cairo

Cairo PR: [68](https://github.com/software-mansion-labs/cairo/pull/68)
This PR also removes unused and obsolete libfuncs versions for cairo0

Rename library functions. Remove unused ones

---

scripts/install_cairo_bindings.sh

The comments in the install script are misleading and make it harder to read and understand the code.

Fix misleading comments in the bindings installing script
